# Generated by Django 5.2.1 on 2025-05-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'menu_item')},
        ),
    ]
